# Copyright 2023 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""SLURM configuration option tokens."""

from typing import Callable, NamedTuple, Optional


class _Callback(NamedTuple):
    """Data struct for holding conf option parser and render methods."""

    parse: Optional[Callable] = None
    render: Optional[Callable] = None


class _SlurmConfOpts(NamedTuple):
    """Top-level SLURM configuration options."""

    Include: _Callback = _Callback()
    AccountingStorageBackupHost: _Callback = _Callback()
    AccountingStorageEnforce: _Callback = _Callback()
    AccountStorageExternalHost: _Callback = _Callback()
    AccountingStorageHost: _Callback = _Callback()
    AccountingStorageParameters: _Callback = _Callback()
    AccountingStoragePass: _Callback = _Callback()
    AccountingStoragePort: _Callback = _Callback()
    AccountingStorageTRES: _Callback = _Callback()
    AccountingStorageType: _Callback = _Callback()
    AccountingStorageUser: _Callback = _Callback()
    AccountingStoreFlags: _Callback = _Callback()
    AcctGatherNodeFreq: _Callback = _Callback()
    AcctGatherEnergyType: _Callback = _Callback()
    AcctGatherInterconnectType: _Callback = _Callback()
    AcctGatherFilesystemType: _Callback = _Callback()
    AcctGatherProfileType: _Callback = _Callback()
    AllowSpecResourcesUsage: _Callback = _Callback()
    AuthAltTypes: _Callback = _Callback()
    AuthAltParameters: _Callback = _Callback()
    AuthInfo: _Callback = _Callback()
    AuthType: _Callback = _Callback()
    BatchStartTimeout: _Callback = _Callback()
    BcastExclude: _Callback = _Callback()
    BcastParameters: _Callback = _Callback()
    BurstBufferType: _Callback = _Callback()
    CliFilterPlugins: _Callback = _Callback()
    ClusterName: _Callback = _Callback()
    CommunicationParameters: _Callback = _Callback()
    CompleteWait: _Callback = _Callback()
    CoreSpecPlugin: _Callback = _Callback()
    CpuFreqDef: _Callback = _Callback()
    CpuFreqGovernors: _Callback = _Callback()
    CredType: _Callback = _Callback()
    DebugFlags: _Callback = _Callback()
    DefCpuPerGPU: _Callback = _Callback()
    DefMemPerCPU: _Callback = _Callback()
    DefMemPerGPU: _Callback = _Callback()
    DefMemPerNode: _Callback = _Callback()
    DependencyParameters: _Callback = _Callback()
    DisableRootJobs: _Callback = _Callback()
    EioTimeout: _Callback = _Callback()
    EnforcePartLimits: _Callback = _Callback()
    Epilog: _Callback = _Callback()
    EpilogMsgTime: _Callback = _Callback()
    EpilogSlurmctld: _Callback = _Callback()
    ExtSensorsFreq: _Callback = _Callback()
    ExtSensorsType: _Callback = _Callback()
    FairShareDampeningFactor: _Callback = _Callback()
    FederationParameters: _Callback = _Callback()
    FirstJobId: _Callback = _Callback()
    GetEnvTimeout: _Callback = _Callback()
    GresTypes: _Callback = _Callback()
    GroupUpdateForce: _Callback = _Callback()
    GroupUpdateTime: _Callback = _Callback()
    GpuFreqDef: _Callback = _Callback()
    HealthCheckInterval: _Callback = _Callback()
    HealthCheckNodeState: _Callback = _Callback()
    HealthCheckProgram: _Callback = _Callback()
    InactiveLimit: _Callback = _Callback()
    InteractiveStepOptions: _Callback = _Callback()
    JobAcctGatherType: _Callback = _Callback()
    JobAcctGatherFrequency: _Callback = _Callback()
    JobAcctGatherParams: _Callback = _Callback()
    JobCompHost: _Callback = _Callback()
    JobCompLoc: _Callback = _Callback()
    JobCompParams: _Callback = _Callback()
    JobCompPass: _Callback = _Callback()
    JobCompPort: _Callback = _Callback()
    JobCompType: _Callback = _Callback()
    JobCompUser: _Callback = _Callback()
    JobContainerType: _Callback = _Callback()
    JobFileAppend: _Callback = _Callback()
    JobRequeue: _Callback = _Callback()
    JobSubmitPlugins: _Callback = _Callback()
    KillOnBadExit: _Callback = _Callback()
    KillWait: _Callback = _Callback()
    MaxBatchRequeue: _Callback = _Callback()
    NodeFeaturesPlugins: _Callback = _Callback()
    LaunchParameters: _Callback = _Callback()
    Licenses: _Callback = _Callback()
    LogTimeFormat: _Callback = _Callback()
    MailDomain: _Callback = _Callback()
    MailProg: _Callback = _Callback()
    MaxArraySize: _Callback = _Callback()
    MaxJobCount: _Callback = _Callback()
    MaxJobId: _Callback = _Callback()
    MaxMemPerCPU: _Callback = _Callback()
    MaxMemPerNode: _Callback = _Callback()
    MaxNodeCount: _Callback = _Callback()
    MaxStepCount: _Callback = _Callback()
    MaxTasksPerNode: _Callback = _Callback()
    MCSParameters: _Callback = _Callback()
    MCSPlugin: _Callback = _Callback()
    MessageTimeout: _Callback = _Callback()
    MinJobAge: _Callback = _Callback()
    MpiDefault: _Callback = _Callback()
    MpiParams: _Callback = _Callback()
    OverTimeLimit: _Callback = _Callback()
    PluginDir: _Callback = _Callback()
    PlugStackConfig: _Callback = _Callback()
    PowerParameters: _Callback = _Callback()
    PowerPlugin: _Callback = _Callback()
    PreemptMode: _Callback = _Callback()
    PreemptParameters: _Callback = _Callback()
    PreemptType: _Callback = _Callback()
    PreemptExemptTime: _Callback = _Callback()
    PrEpParameters: _Callback = _Callback()
    PrEpPlugins: _Callback = _Callback()
    PriorityCalcpPeriod: _Callback = _Callback()
    PriorityDecayHalfLife: _Callback = _Callback()
    PriorityFavorSmall: _Callback = _Callback()
    PriorityFlags: _Callback = _Callback()
    PriorityMaxAge: _Callback = _Callback()
    PriorityParameters: _Callback = _Callback()
    PrioritySiteFactorParameters: _Callback = _Callback()
    PrioritySiteFactorPlugin: _Callback = _Callback()
    PriorityType: _Callback = _Callback()
    PriorityUsageResetPeriod: _Callback = _Callback()
    PriorityWeightAge: _Callback = _Callback()
    PriorityWeightAssoc: _Callback = _Callback()
    PriorityWeightFairShare: _Callback = _Callback()
    PriorityWeightJobSize: _Callback = _Callback()
    PriorityWeightPartition: _Callback = _Callback()
    PriorityWeightQOS: _Callback = _Callback()
    PriorityWeightTRES: _Callback = _Callback()
    PrivateData: _Callback = _Callback()
    ProctrackType: _Callback = _Callback()
    Prolog: _Callback = _Callback()
    PrologEpilogTimeout: _Callback = _Callback()
    PrologFlags: _Callback = _Callback()
    PrologSlurmctld: _Callback = _Callback()
    PropagatePrioProcess: _Callback = _Callback()
    PropagateResourceLimits: _Callback = _Callback()
    PropagateResourceLimitsExcept: _Callback = _Callback()
    RebootProgram: _Callback = _Callback()
    ReconfigFlags: _Callback = _Callback()
    RequeueExit: _Callback = _Callback()
    RequeueExitHold: _Callback = _Callback()
    ResumeFailProgram: _Callback = _Callback()
    ResumeProgram: _Callback = _Callback()
    ResumeRate: _Callback = _Callback()
    ResumeTimeout: _Callback = _Callback()
    ResvEpilog: _Callback = _Callback()
    ResvOverRun: _Callback = _Callback()
    ResvProlog: _Callback = _Callback()
    ReturnToService: _Callback = _Callback()
    RoutePlugin: _Callback = _Callback()
    SchedulerParameters: _Callback = _Callback()
    SchedulerTimeSlice: _Callback = _Callback()
    SchedulerType: _Callback = _Callback()
    ScronParameters: _Callback = _Callback()
    SelectType: _Callback = _Callback()
    SelectTypeParameters: _Callback = _Callback()
    SlurmctldAddr: _Callback = _Callback()
    SlurmctldDebug: _Callback = _Callback()
    SlurmctldHost: _Callback = _Callback()
    SlurmctldLogFile: _Callback = _Callback()
    SlurmctldParameters: _Callback = _Callback()
    SlurmctldPidFile: _Callback = _Callback()
    SlurmctldPort: _Callback = _Callback()
    SlurmctldPrimaryOffProg: _Callback = _Callback()
    SlurmctldPrimaryOnProg: _Callback = _Callback()
    SlurmctldSyslogDebug: _Callback = _Callback()
    SlurmctldTimeout: _Callback = _Callback()
    SlurmdDebug: _Callback = _Callback()
    SlurmdLogFile: _Callback = _Callback()
    SlurmdParameters: _Callback = _Callback()
    SlurmdPidFile: _Callback = _Callback()
    SlurmdPort: _Callback = _Callback()
    SlurmdSpoolDir: _Callback = _Callback()
    SlurmdSyslogDebug: _Callback = _Callback()
    SlurmdTimeout: _Callback = _Callback()
    SlurmdUser: _Callback = _Callback()
    SlurmSchedLogFile: _Callback = _Callback()
    SlurmSchedLogLevel: _Callback = _Callback()
    SlurmUser: _Callback = _Callback()
    SrunEpilog: _Callback = _Callback()
    SrunPortRange: _Callback = _Callback()
    SrunProlog: _Callback = _Callback()
    StateSaveLocation: _Callback = _Callback()
    SuspendExcNodes: _Callback = _Callback()
    SuspendExcParts: _Callback = _Callback()
    SuspendExcStates: _Callback = _Callback()
    SuspendProgram: _Callback = _Callback()
    SuspendRate: _Callback = _Callback()
    SuspendTime: _Callback = _Callback()
    SuspendTimeout: _Callback = _Callback()
    SwitchParameters: _Callback = _Callback()
    SwitchType: _Callback = _Callback()
    TaskEpilog: _Callback = _Callback()
    TaskPlugin: _Callback = _Callback()
    TaskPluginParam: _Callback = _Callback()
    TaskProlog: _Callback = _Callback()
    TCPTimeout: _Callback = _Callback()
    TmpFS: _Callback = _Callback()
    TopologyParam: _Callback = _Callback()
    TopologyPlugin: _Callback = _Callback()
    TrackWCKey: _Callback = _Callback()
    TreeWidth: _Callback = _Callback()
    UnkillableStepProgram: _Callback = _Callback()
    UnkillableStepTimeout: _Callback = _Callback()
    UsePAM: _Callback = _Callback()
    VSizeFactor: _Callback = _Callback()
    WaitTime: _Callback = _Callback()
    X11Parameters: _Callback = _Callback()


class _NodeConfOpts(NamedTuple):
    """SLURM node configuration options."""

    NodeName: _Callback = _Callback()
    NodeHostname: _Callback = _Callback()
    NodeAddr: _Callback = _Callback()
    BcastAddr: _Callback = _Callback()
    Boards: _Callback = _Callback()
    CoreSpecCount: _Callback = _Callback()
    CoresPerSocket: _Callback = _Callback()
    CpuBind: _Callback = _Callback()
    CPUs: _Callback = _Callback()
    CpuSpecList: _Callback = _Callback()
    Features: _Callback = _Callback()
    Gres: _Callback = _Callback()
    MemSpecLimit: _Callback = _Callback()
    Port: _Callback = _Callback()
    Procs: _Callback = _Callback()
    RealMemory: _Callback = _Callback()
    Reason: _Callback = _Callback()
    Sockets: _Callback = _Callback()
    SocketsPerBoard: _Callback = _Callback()
    State: _Callback = _Callback()
    ThreadsPerCore: _Callback = _Callback()
    TmpDisk: _Callback = _Callback()
    Weight: _Callback = _Callback()


class _DownNodeConfOpts(NamedTuple):
    """SLURM down node configuration options."""

    DownNodes: _Callback = _Callback()
    Reason: _Callback = _Callback()
    State: _Callback = _Callback()


class _FrontendNodeConfOpts(NamedTuple):
    """SLURM frontend node configuration options."""

    FrontendName: _Callback = _Callback()
    FrontendAddr: _Callback = _Callback()
    AllowGroups: _Callback = _Callback()
    AllowUsers: _Callback = _Callback()
    DenyGroups: _Callback = _Callback()
    DenyUsers: _Callback = _Callback()
    Port: _Callback = _Callback()
    Reason: _Callback = _Callback()
    State: _Callback = _Callback()


class _NodeSetConfOpts(NamedTuple):
    """SLURM nodeset configuration options."""

    NodeSet: _Callback = _Callback()
    Feature: _Callback = _Callback()
    Nodes: _Callback = _Callback()


class _PartitionConfOpts(NamedTuple):
    """SLURM partition configuration options."""

    PartitionName: _Callback = _Callback()
    AllocNodes: _Callback = _Callback()
    AllowAccounts: _Callback = _Callback()
    AllowGroups: _Callback = _Callback()
    AllowQos: _Callback = _Callback()
    Alternate: _Callback = _Callback()
    CpuBind: _Callback = _Callback()
    Default: _Callback = _Callback()
    DefaultTime: _Callback = _Callback()
    DefCpuPerGPU: _Callback = _Callback()
    DefMemPerCPU: _Callback = _Callback()
    DefMemPerGPU: _Callback = _Callback()
    DefMemPerNode: _Callback = _Callback()
    DenyAccounts: _Callback = _Callback()
    DenyQos: _Callback = _Callback()
    DisableRootJobs: _Callback = _Callback()
    ExclusiveUser: _Callback = _Callback()
    GraceTime: _Callback = _Callback()
    Hidden: _Callback = _Callback()
    LLN: _Callback = _Callback()
    MaxCPUsPerNode: _Callback = _Callback()
    MaxCPUsPerSocket: _Callback = _Callback()
    MaxMemPerCPU: _Callback = _Callback()
    MaxMemPerNode: _Callback = _Callback()
    MaxNodes: _Callback = _Callback()
    MaxTime: _Callback = _Callback()
    MinNodes: _Callback = _Callback()
    Nodes: _Callback = _Callback()
    OverSubscribe: _Callback = _Callback()
    OverTimeLimit: _Callback = _Callback()
    PowerDownOnIdle: _Callback = _Callback()
    PreemptMode: _Callback = _Callback()
    PriorityJobFactor: _Callback = _Callback()
    PriorityTier: _Callback = _Callback()
    QOS: _Callback = _Callback()
    ReqResv: _Callback = _Callback()
    ResumeTimeout: _Callback = _Callback()
    RootOnly: _Callback = _Callback()
    SelectTypeParameters: _Callback = _Callback()
    State: _Callback = _Callback()
    SuspendTime: _Callback = _Callback()
    SuspendTimeout: _Callback = _Callback()
    TRESBillingWeights: _Callback = _Callback()


SlurmConfOpts = _SlurmConfOpts()
NodeConfOpts = _NodeConfOpts()
DownNodeConfOpts = _DownNodeConfOpts()
FrontendNodeConfOpts = _FrontendNodeConfOpts()
NodeSetConfOpts = _NodeSetConfOpts()
PartitionConfOpts = _PartitionConfOpts()
